-- CreateEnum
CREATE TYPE "ProviderType" AS ENUM ('PROMOTEUR', 'PARTENARIAT', 'ARCHITECTE', 'SOC_TRAVAUX_PUBLICS', 'SOC_TRAVAUX_CONSTRUCTION', 'NOTAIRE', 'PARTICULIER', 'AUTRE');

-- AlterTable
ALTER TABLE "Provider" ADD COLUMN     "type" "ProviderType" NOT NULL DEFAULT 'PARTICULIER';
